export enum Controls {
  forward = "forward",
  backward = "backward",
  leftward = "leftward",
  rightward = "rightward",
  jump = "jump",
  run = "run",
  action1 = "action1",
  action2 = "action2",
  action3 = "action3",
  action4 = "action4",
  action5 = "action5",
  action6 = "action6",
  action7 = "action7",
  action8 = "action8",
  action9 = "action9",
  action0 = "action0",
  actionF = "actionF",
  actionQ = "actionQ",
  actionE = "actionE",
  actionR = "actionR",
}
